# fly.toml app configuration file generated for cringepartybot on 2023-10-22T12:18:12+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cringeparty"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
